### ISSUE TITLE
Feature Request: Custom "Alphabet'

### ISSUE THREAD

**Issue by GianniBYoung** [sathishmanohar/quick-buffer-jump#3]
I would love to see the option to change the provided alphabet for labeling jumps from `abcd.....` to something more ergonomic such as `qwerty` or `asdf`

**Comment by sathishmanohar** [comment]
Sure. I thought about this. Based on my workflow having the alphabetical order has other benefits like. I just jump to `b` buffer without thinking while working on a feature because I already know the file in that place. I'm sure if it is `asdf` or `qwert` or `uiop` remembering is still possible but I'm afraid it might not be as intuitive.

Please continue using the plugin and let me know if alphabetical order is growing on you. But I definitely understand the appeal of having an option to choose between two approaches. 

I'll make the config option available when there are more users chiming in on this feature.

**Comment by GianniBYoung** [comment]
Thanks for the response and the plan!
